"""empty message

Revision ID: 032e0df545b0
Revises: 197c4a592bc8
Create Date: 2020-05-13 04:08:10.598147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032e0df545b0'
down_revision = '197c4a592bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('price', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'price')
    # ### end Alembic commands ###
